data <- read.csv('household_power_consumption.txt', sep=';', na.strings='?')
data <- transform(data, Date=strptime(paste(as.character(Date),as.character(Time)), format='%d/%m/%Y %H:%M:%S'))
data <- subset(data, Date>="2007-02-01 00:00:00" & Date<="2007-02-02 23:59:59")
png('plot3.png', width=480, height=480)
with(data, plot(Date, Sub_metering_1, xlab="", ylab="Energy sub metering", main="", type="l", col="black"))
with(data, lines(Date, Sub_metering_2, type="l", col="red"))
with(data, lines(Date, Sub_metering_3, type="l", col="blue"))
legend("topright", col=c("black","red","blue"), lty=1, lwd=1, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()