data <- read.csv('household_power_consumption.txt', sep=';', na.strings='?')
data <- transform(data, Date=as.Date(Date,'%d/%m/%Y'))
data <- subset(data, Date>="2007-02-01" & Date<="2007-02-02")
png('plot1.png', width=480, height=480)
hist(data$Global_active_power, col='red', ylab="Frequency", xlab="Global Active Power (kilowatts)", main="Global Active Power")
dev.off()